name: Build
on: [ push ]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm run install

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: 'dist'
          path: 'dist'
